name: mango_wear
version: 1.0.0
description: Wrapper for Mango Wear API
repository: https://github.com/louisevanderlith/wear
homepage: https://github.com/louisevanderlith/wear
environment:
  sdk: '>=2.0.0 < 3.0.0'
dependencies:
  mango_ui: '^1.0.3'